### ISSUE TITLE
PathWeaver project using wrong values for Max Velocity, Max Acceleration, and Wheel Base (in inches should be in meters)

### ISSUE THREAD

**Issue by 22lejo** [team178/2021RomiBot#1]
Needs to be fixed soon as group leaders need to test them. Should be pretty easy, constants.java should have everything there.

![image](https://user-images.githubusercontent.com/59667770/107284230-74c2e600-6a2b-11eb-90a6-3fcb083dc433.png)

**Comment by AM2i9** [comment]
Have you tried:
![image](https://user-images.githubusercontent.com/52932656/107854545-7c4b0c00-6dea-11eb-9da3-c66947beaa9f.png)

**Comment by 22lejo** [comment]
Yeah I know I can just move to meters, but then it just messes PathWeaver up for whatever reason (https://github.com/team178/2021RomiBot/issues/4). Also I want characterize the Romi Bot instead of using what's in the constants (probably gonna do that today)

**Comment by 22lejo** [comment]
Everything in meters now, still want to play around with Max Velocity and Max Acceleration. Check latest commit and https://github.com/team178/2021RomiBot/issues/4 which is now closed.

**Comment by AM2i9** [comment]
It may be messed up because it doesn't convert the values that are already in there as inches into meters?

**Comment by 22lejo** [comment]
Well from what I can interpret from my tests. It seems to be because of the opposite of what you said, and maybe something with how PathWeaver creates a default path when you create a new one.
